---
hero_image: images / colorful-creations.png
theme: màu vàng
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, thiết kế-0, lập trình-1, phys-comp-0, sản xuất-0, cộng đồng-0
title: Sáng tạo đầy màu sắc
description: Tạo màu tùy chỉnh của riêng bạn và sử dụng chúng để tạo ra một áp phích đầy màu sắc.
original_url: https://codeclubprojects.org/en-GB/python/colourful-creations
interests: nghệ thuật
technologies: con trăn
site_areas: dự án
hardware: ''
software: con trăn
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Giới thiệu
  - 
    title: Sử dụng mã màu hex
  - 
    title: Từ điển màu
  - 
    title: 'Thách thức: Nhiều màu sắc hơn!'
  - 
    title: 'Thách thức: Tạo một áp phích'
