---
hero_image: Kuvien / värikäs-creations.png
theme: keltainen
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, ohjelmointi-1, phys-comp-0, valmistus-0, yhteisö-0
title: Värikäs luomukset
description: Luo omat värilliset värit ja käytä niitä luomalla värikäs juliste.
original_url: https://codeclubprojects.org/en-GB/python/colourful-creations
interests: taide
technologies: pytonkäärme
site_areas: hankkeet
hardware: ''
software: pytonkäärme
version: 3
last_tested: 01.1.2017
steps:
  - 
    title: esittely
  - 
    title: Käytä heksadesimaaleja
  - 
    title: Väri-sanakirja
  - 
    title: 'Haaste: Lisää värejä!'
  - 
    title: 'Haaste: Luo juliste'
