hero_image: images/colourful-creations.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Colourful Creations
description: Kreiere deine eigenen Farben und benutze sie, um ein buntes Poster anzufertigen.
original_url: https://codeclubprojects.org/en-GB/python/colourful-creations
interests: 'art and design'
technologies: python
site_areas: codeclub, python
steps:
- title: Einführung
- title: Hexadezimalcodes benutzen
- title: Ein Farbwörterbuch
- title: 'Aufgabe: Noch mehr Farben!'
- title: 'Aufgabe: Fertige ein Poster an'

