---
hero_image: images/colourful-creations.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Creații colorate
description: Creează-ți propriile culori și folosește-le pentru a crea un afiș colorat.
original_url: https://codeclubprojects.org/en-GB/python/colourful-creations
interests: art
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - title: Introducere
  - title: Folosind coduri de culori hexazecimale
  - title: Un dicționar de culori
  - title: 'Provocare: Mai multe culori!'
  - title: 'Provocare: Creează un afiș'
