---
hero_image: images / colorful-creations.png
theme: żółty
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Kolorowe kreacje
description: Twórz własne niestandardowe kolory i używaj ich do tworzenia kolorowego plakatu.
original_url: https://codeclubprojects.org/en-GB/python/colourful-creations
interests: art
technologies: pyton
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Wprowadzenie
  - 
    title: Używanie kodów kolorów hex
  - 
    title: Słownik kolorów
  - 
    title: 'Wyzwanie: więcej kolorów!'
  - 
    title: 'Wyzwanie: Stwórz plakat'
