---
hero_image: images / färgstarka-creations.png
theme: gul
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programmering-1, phys-comp-0, tillverkning-0, community-0
title: Färgglada skapelser
description: Skapa egna egna färger och använd dem för att skapa en färgstark affisch.
original_url: https://codeclubprojects.org/en-GB/python/colourful-creations
interests: konst
technologies: pytonorm
site_areas: projekt
hardware: ''
software: pytonorm
version: 3
last_tested: 2017/01/01
steps:
  - 
    title: Introduktion
  - 
    title: Använda hex färgkoder
  - 
    title: En färgordlista
  - 
    title: 'Utmaning: Fler färger!'
  - 
    title: 'Utmaning: Skapa en affisch'
