---
hero_image: images/colourful-creations.png
theme: jaune
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, conception-0, programmation-1, phys-comp-0, fabrication-0, communauté-0
title: Créations colorées
description: Crée tes propres couleurs personalisées, et utilise les pour créer un poster haut en couleurs.
original_url: https://codeclubprojects.org/fr-FR/python/colourful-creations/
interests: art
technologies: python
site_areas: projets
hardware: ''
software: python
version: 3
last_tested: 01-01-2017
steps:
  - 
    title: Introduction
  - 
    title: Utilisation des codes hexadécimaux de couleurs
  - 
    title: Un dictionnaire de couleurs
  - 
    title: 'Défi : Plus de couleurs !'
  - 
    title: 'Défi : Crée un affiche'
