---
hero_image: images/colourful-creations.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Creazioni colorate
description: Crea i tuoi colori personalizzati e usali per creare un coloratissimo poster.
original_url: https://codeclubprojects.org/en-GB/python/colourful-creations
interests: art
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduzione
  - 
    title: Come usare i codici esadecimali dei colori
  - 
    title: Un dizionario di colori
  - 
    title: 'Sfida: Altri colori!'
  - 
    title: 'Sfida: Crea un poster'
