---
hero_image: images/colourful-creations.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Renkli Tasarımlar
description: Kendi özel renklerinizi oluşturun ve renkli bir poster oluşturmak için
  bunları kullanın.
original_url: https://codeclubprojects.org/en-GB/python/colourful-creations
interests: art
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Giriş
- title: Onaltılık renk kodlarını kullanma
- title: Bir Renk Sözlüğü
  completion:
  - engaged
  - internal
- title: 'Meydan Okuma: Daha fazla renk!'
- title: 'Meydan Okuma: Bir poster yaratın'
